modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "msd"
version = "@version@"
displayName = "MTR Station Decoration Addon"
authors = "AIDA64S,Santorsia,Zbx1425"
description = "A Station Decoration Addon for the Minecraft Transit Railway Mod"
logoFile = "icon.png"

[[dependencies.msd]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.msd]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"

[[dependencies.msd]]
modId = "mtr"
mandatory = true
versionRange = "[@mtrVersion@]"
ordering = "AFTER"
side = "BOTH"